// Mocks generated by Mockito 5.4.4 from annotations
// in app_ecommerce/test/widgets/product_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_ecommerce/core/providers.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatalogState_0 extends _i1.SmartFake implements _i2.CatalogState {
  _FakeCatalogState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatalogViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogViewModel extends _i1.Mock implements _i2.CatalogViewModel {
  MockCatalogViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i2.CatalogState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.CatalogState>.empty(),
          )
          as _i4.Stream<_i2.CatalogState>);

  @override
  _i2.CatalogState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCatalogState_0(this, Invocation.getter(#state)),
          )
          as _i2.CatalogState);

  @override
  set state(_i2.CatalogState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.CatalogState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeCatalogState_0(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.CatalogState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadProducts() =>
      (super.noSuchMethod(
            Invocation.method(#loadProducts, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> filterByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#filterByCategory, [category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool updateShouldNotify(_i2.CatalogState? old, _i2.CatalogState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.RemoveListener addListener(
    _i5.Listener<_i2.CatalogState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i3.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
