// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXTsZN_OAfiQd6MzVyrjNsKGveJ4nBkc',
    appId: '1:28373228702:web:1518b5c575e2107bd86f8f',
    messagingSenderId: '28373228702',
    projectId: 'app-ecommerce-flutter-eb6fe',
    authDomain: 'app-ecommerce-flutter-eb6fe.firebaseapp.com',
    storageBucket: 'app-ecommerce-flutter-eb6fe.firebasestorage.app',
    measurementId: 'G-RWPLV0B8H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRnKYa3x0cp0zPe6omhQLAMz5ayI6RXQ',
    appId: '1:28373228702:android:6eebb07f7a2ed329d86f8f',
    messagingSenderId: '28373228702',
    projectId: 'app-ecommerce-flutter-eb6fe',
    storageBucket: 'app-ecommerce-flutter-eb6fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tcxJQfymYn1mnDokvgexgdL3NrccnvY',
    appId: '1:28373228702:ios:3efb5beedbfe508dd86f8f',
    messagingSenderId: '28373228702',
    projectId: 'app-ecommerce-flutter-eb6fe',
    storageBucket: 'app-ecommerce-flutter-eb6fe.firebasestorage.app',
    iosBundleId: 'com.example.appEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tcxJQfymYn1mnDokvgexgdL3NrccnvY',
    appId: '1:28373228702:ios:3efb5beedbfe508dd86f8f',
    messagingSenderId: '28373228702',
    projectId: 'app-ecommerce-flutter-eb6fe',
    storageBucket: 'app-ecommerce-flutter-eb6fe.firebasestorage.app',
    iosBundleId: 'com.example.appEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvXTsZN_OAfiQd6MzVyrjNsKGveJ4nBkc',
    appId: '1:28373228702:web:2f5810e76476be30d86f8f',
    messagingSenderId: '28373228702',
    projectId: 'app-ecommerce-flutter-eb6fe',
    authDomain: 'app-ecommerce-flutter-eb6fe.firebaseapp.com',
    storageBucket: 'app-ecommerce-flutter-eb6fe.firebasestorage.app',
    measurementId: 'G-MWG3GBB92Q',
  );
}
